spotify:
  client-id: spotify_client_id
  client-secret: spotfy_client_secret

youtube:
  key: youtube_key # is this still necessary? IIRC this has been completely removed.

spring:
  discord:
    token: discord_token
    online-status: DO_NOT_DISTURB

  datasource:
    url: jdbc:mariadb://localhost:3306/musicbot
    username: root
    password: ""
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 5

    properties:
      hibernate:
        enable_lazy_load_no_trans: true # investigate this, I don't remember why I added it initially
