spotify:
  client-id: spotify_client_id
  client-secret: spotfy_client_secret

youtube:
  key: youtube_key


spring:
  discord:
    token: discord_token
    online-status: DO_NOT_DISTURB
    guild-id: 0

  datasource:
    url: jdbc:mariadb://localhost:3306/musicbot
    username: root
    password: ""
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

    properties:
      hibernate:
        enable_lazy_load_no_trans: true