spotify:
  client-id: spotify_client_id
  client-secret: spotfy_client_secret

spring:
  discord:
    token: discord_token
    online-status: DO_NOT_DISTURB

  datasource:
    url: jdbc:mariadb://localhost:3306/musicbot
    username: root
    password: ""
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 5
